seed: 42

date_range:
  start: "2024-01-01"
  end: "2024-12-31"

tables:
  MSTR_ARTICULOS:
    records: 5000

  MSTR_PROVEEDORES:
    records: 800

  MSTR_TIENDAS:
    records: 150

  CRM_MIEMBROS:
    records: 50000

  TRANS_VENTAS:
    records: 1000000

  MKT_VISITAS_CANAL:
    records: 1800000

  INV_STOCK_DIARIO:
    records: 750000

  POST_DEVOLUCIONES:
    records: 50000
